services:
  api:
    container_name: outlook-cleaner-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT:-4000}
    ports:
      - '${PORT:-4000}'
      #- '4000:4000'
    networks:
      - outlook.net

  web:
    container_name: outlook-cleaner-web
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_AZURE_CLIENT_ID: ${VITE_AZURE_CLIENT_ID}
        VITE_AZURE_TENANT_ID: ${VITE_AZURE_TENANT_ID}
        VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
    ports:
      - '80'
      #- '80:80'
    depends_on:
      - api
    networks:
      - outlook.net

networks:
  outlook.net:
    name: outlook.net
    driver: bridge
